dist: trusty
sudo: required
before_install: sudo apt-get install build-essential debhelper devscripts dh-make
  lintian
install: true
script: make build
notifications:
  slack:
    secure: dNACOmk78ijDvaUM/lVamiKi2wuj3fyqgKw9XgHeVy/la8ie7NvinBLlNsrOuL/iM6BG2mX4gp5x9Y+TOevnIW0exeIyDVnkPhcAGzyTrE+6RMeUxzBIWuGx8KPi2K90HuIOOcMEQemmjw6ATeMf5VG+ZlVy1Un5JZfg3PlIcvmH2mzqy9KzSyXq0p4OvqAMBlLFvWjDwlrpqjLhfnER52NvQFOIsRM87n2eY9gYktyfjdXnfSbvt6iPGo0GVsWwep/OQ3wgVSFfl105HokKpJ28RSv6ENwZPCPnbP8zNsd2fl0AwmGovGKG/Ue0PjGFc+6+BrmRlI6srS0RZ5CXZSthwgw0Y4Wye2VmyVcw79wM1AtJqJLuevPhPwkk1AVagK4FcTjyO06gpkGLtG5QlLTVkLKf5X1aJvRp+ibZJlv8Ue3voiRU8OhFbzme6BXcgzjKU5BDcc5CofZHPmm67oqx6Rqgxr9e5YIqTkR0MWMpBx6WMGclsF2a/fN3EottslYyDEtcjCdjVkPiSUehuD7FTOH5qjnGPRcZtjTTXQ6EeFccv29zFk83lAJapAKob64hyfNUPD3A0KQDxVrR89MMc8FxP+GIYElzIS46icH5BOZBFiN7wXduwrrxYMMB2SgpHhLtNluGfL1+BfBmK1ooc7IfWmqU6bi6wafurBE=
